### ISSUE TITLE
Module '"nest-postgres"' has no exported member 'PostgresModule'.

### ISSUE THREAD

**Issue by GrimAveira** [Tony133/nestjs-postgres#650]
Where did the "dist" folder go, where do I import the PostgresModule module from?

**Comment by Tony133** [comment]
Hi @GrimAveira, maybe during the release of the new version failed the build , I create a new version of the package, so try again

**Comment by Tony133** [comment]
@GrimAveira  install this version: `npm install nest-postgres@0.0.13`, now it should go
